lab50:
  files:
   - !include caso_01.txt
   - !include caso_02.txt
   - !include caso_03.txt
   - !include caso_04.txt
   - !include caso_05.txt
   - !include caso_06.txt
   - !include ejercicio1.c
    
